### ISSUE TITLE
explicit-exit-notify is only valid in UDP mode, if present with TCP profile, connection fails.

### ISSUE THREAD

**Issue by ab77** [Zomboided/service.vpn.manager.providers#14]
https://github.com/Zomboided/service.vpn.manager.providers/blob/ddd70fac87f80867aa80b0a8b3d7872ca97a06ae/PureVPN/TEMPLATE.txt#L18

`explicit-exit-notify` is only valid in UDP mode, if present with TCP profile, connection fails.

```
--explicit-exit-notify [n]
In UDP client mode or point-to-point mode, send server/peer an exit notification if tunnel is restarted or OpenVPN process is exited. In client mode, on exit/restart, this option will tell the server to immediately close its client instance object rather than waiting for a timeout. The n parameter (default=1) controls the maximum number of attempts that the client will try to resend the exit notification message. OpenVPN will not send any exit notifications unless this option is enabled.
```
See, https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage

**Comment by Zomboided** [comment]
You're right here, but for some reason I noticed this early on and wrote some explicit code to strip it.  I'll check in a change to the template, but it's not really required for my addon and the same problem might exist in other providers (which I'd also be happy to fix)

**Comment by Zomboided** [comment]
There were only a few, so I fixed them all.  This shouldn't be an issue now
