### ISSUE TITLE
Request to update SaferVPN metadata

### ISSUE THREAD

**Issue by sebstepien** [Zomboided/service.vpn.manager.providers#20]
SaferVPN metadata is not up to date and fails to connect.

**Comment by Zomboided** [comment]
Thanks, I'll take a look and update them when I get a chance

**Comment by sebstepien** [comment]
I made the necessary changes, and would like to create a pull request. What is the process for this repository?

**Comment by Zomboided** [comment]
Do the change and I'll review it. If it's a change to the template and/or cert we'll be good. If it's location changes I might need to generate them. Go ahead tho, thanks

**Comment by sebstepien** [comment]
I don't have permission to push a branch up for you to review. I am more familiar with bitbucket than github.

**Comment by Zomboided** [comment]
You should just be able to fork the repo, make the changes and push them back. Or you can post them here and I'll look at them and integrate them myself

**Comment by Zomboided** [comment]
Change integrated
