### ISSUE TITLE
Cyberghost has changed authentication algorithm to SHA256

### ISSUE THREAD

**Issue by taaning** [Zomboided/service.vpn.manager.providers#23]
https://support.cyberghostvpn.com/hc/en-us/articles/115003160293-Updates-to-packet-authentication

Therefor the default auth should be changed from md5 to sha256.

Thank you

**Comment by Zomboided** [comment]
I just committed this, thanks for making me aware.  If you're running cyberghost you should see a message pop up in the next couple of days when you connect that there are updates available and that you need to revalidate the connections
