### ISSUE TITLE
express vpn

### ISSUE THREAD

**Issue by nickshe89** [Zomboided/service.vpn.manager.providers#24]
hello can you fix express vpn please

**Comment by Zomboided** [comment]
If you want me to take this seriously, get a log.  I'm not going to make any effort to guess what you think is wrong.

**Comment by nickshe89** [comment]
sorry i forget post a log im very sorry

https://pastebin.com/XD3rf5fR

thanks

**Comment by Zomboided** [comment]
That location is not responding.  Maybe it's gone away.

The list of locations are here
https://www.expressvpn.com/support/vpn-setup/manual-config-for-windows-xp-vista-7-8-with-openvpn/#download
I don't have an expressvpn account.  If you think a location is wrong or
missing, then get the ovpn file for the location that's not working and
paste it in here after you've removed the text between <key> and </key> and
<cert> and </cert>

**Comment by nickshe89** [comment]
you want me send you a email with my username and password make easy for you

**Comment by nickshe89** [comment]
dev tun
fast-io
persist-key
persist-tun
nobind
remote uk-berkshire-ca-version-2.expressnetw.com 1195

remote-random
pull
comp-lzo
tls-client
verify-x509-name Server name-prefix
ns-cert-type server
key-direction 1
route-method exe
route-delay 2
tun-mtu 1500
fragment 1300
mssfix 1450
verb 3
cipher AES-256-CBC
keysize 256
auth SHA512
sndbuf 524288
rcvbuf 524288
auth-user-pass

**Comment by Zomboided** [comment]
There's already a berkshire connection.  I think the UK ones are :
berkshire
berkshire 2
chessington
kent
london
maidenhead

Are you saying that chessington has gone away?  Is this fix here just to
delete that location, or am I missing new UK locations too?

**Comment by nickshe89** [comment]
sorry i try connect different locations but not working mate

**Comment by Zomboided** [comment]
can you connect to kent and get me the log please...I tried to ping chessington and it didn't respond - which is what I saw in the log.  I've just pinged the kent location now and that's responding.

Can you also download the kent location and include the text between <ca> and </ca> and paste it here.  This is a shared certificate and isn't unique to you unlike the other stuff in the file.

**Comment by nickshe89** [comment]
my kodi log for kent https://pastebin.com/4b4Rcx3Z but not connect and 

and kent location https://pastebin.com/GSNr6aRG

**Comment by Zomboided** [comment]
This is saying auth failure.  The ca and ta keys are the same and the ovpn
file matches what I have now.
Clear out your private keys (settings/utilities I think) and supply the
kent file when asked for a key.  Maybe your private keys have changed - or
your user ID/password has been entered wrong?
If you can connect after this, try another location that's not the one that
you originally posted about.  ExpressVPN used to use the same key for each
location, maybe this has changed?

**Comment by nickshe89** [comment]
ok i try clear my private keys and try again i  got some message not connect
https://pastebin.com/S0pMc4tt
what you email adderss i can send you my username and password so you can quick look 

thanks

**Comment by nickshe89** [comment]
or skype

**Comment by Zomboided** [comment]
I don't have time to test at the moment, sorry.

Next step is to take what you downloaded - let's use Kent, and bring up a
command line.  You should just be able to type 'openvpn' and press return
and you should see a list of options.
Then enter 'openvpn' followed by the location of the ovpn file you
downloaded.  You should be asked for a username and password.  If this
fails, then the problem is either with the file you download not matching
what the provider expects - at which point you can raise a support ticket -
or your user id/password.  There will be some words returned that include
'auth_fail' I think.  If it works then you'll end up with a message that
says 'Initialisation sequence complete'.  If it works, then i'll borrow
your ID and try myself later this week.

**Comment by nickshe89** [comment]
im on windows 10 so i can not test it sorry

**Comment by nickshe89** [comment]
i fix it i need used different username and password not log in username and password so its working and im very sorry 

thanks

**Comment by Zomboided** [comment]
sure you can - press windows key and r, and enter cmd - you'll have the
command line you need

**Comment by Zomboided** [comment]
ok, good, thanks
