### ISSUE TITLE
IPVanish locations.txt

### ISSUE THREAD

**Issue by Carole214** [Zomboided/service.vpn.manager.providers#32]
Hi I'm new here. I don't know all that much about github yet. However, I have created my own new locations.txt file for IPVanish, using the latest provider update, and the android app. If anyone is interested, I'd be happy to share. I'm running Kodi on a Tinkerboard, and want to thank those who work so hard on addons, especially truly great ones like VPN Manager! :-)

**Comment by Zomboided** [comment]
Regenerating this list so it'll download automatically.  Thanks for pointing out it was out of date (again...)
