### ISSUE TITLE
CyberGhost Domain Changed

### ISSUE THREAD

**Issue by SloppyShovel** [Zomboided/service.vpn.manager.providers#33]
CyberGhost Domain has been changed to 1-nl.cg-dialup.net 

5-nl.cg-dialup.net does not exist anymore

inQonsole

**Comment by Zomboided** [comment]
Thanks, updated

**Comment by Antelox** [comment]
CyberGhost locations changed again. An update is welcome. Thanks!

**Comment by Zomboided** [comment]
I don't have access to Cyberghost you need to change me what's changed
exactly

**Comment by Antelox** [comment]
Me neither! Probably @cristianaghe

**Comment by cristianaghe** [comment]
hi guys, will have a look today!! :) thanks!

**Comment by cristianaghe** [comment]
hey @Antelox can you please describe what errors or issues you are actually seeing so I can identify if any problems from our side?

Thanks so much,
Cristiana
