### ISSUE TITLE
ExpressVPN locations update.

### ISSUE THREAD

**Issue by Mike-KL** [Zomboided/service.vpn.manager.providers#35]
@zomboided How should users go about requesting and/or providing information to ensure ExpressVPN's locations are very latest available?

Reason for this query is I am suddenly having issues with LibreELEC where a particular addon (which constantly blocks know VPN's locations) will not work but very same addon works fine in kodi on a windows PC using ExpressVPN's own windows app.

I note that they appear to have been updated approx 3 months ago but believe some of ExpressVPN locations details may have already been recently updated/modified for UK?

LibreELEC on RPi3 B+ via  VPN Manager

![screenshot000](https://user-images.githubusercontent.com/16574667/54223471-e02a7300-44f7-11e9-8525-305029e6754b.png)

Win10 via ExpressVPN App

<img width="125" alt="Windows Addon" src="https://user-images.githubusercontent.com/16574667/54223529-fb957e00-44f7-11e9-81da-2e2414923864.PNG">

Any help and/or point in right direction appreciated, thanks you very very much for service.vpn.manager
addon.

**Comment by Mike-KL** [comment]
hmmm just to comment that maybe issue was at ExpressVPN end and already resolved.  Last night had issue with particular location (i.e. selected Kent location not working in LibreELEC on rpi) and tonight working fine in Kodi Win10 and LibreELEC on rpi.  Apologies for noise.

**Comment by Zomboided** [comment]
ok, closing
