### ISSUE TITLE
Mullvad has new CA certificate

### ISSUE THREAD

**Issue by yitzhaq** [Zomboided/service.vpn.manager.providers#36]
Hey,

Mullvad changed their CA cert on March 22nd:

https://mullvad.net/en/blog/2018/11/19/all-users-must-update-just-time-celebrate/

Can you regenerate configs, please? Account no. 1234 doesn't seem to work anymore, but 123456 did for me, at least.

https://mullvad.net/en/download/config/

Cheers

**Comment by Zomboided** [comment]
Thanks for the reminded about the magic account number...this is done now
