### ISSUE TITLE
Do a Mullvad pull

### ISSUE THREAD

**Issue by yitzhaq** [Zomboided/service.vpn.manager.providers#48]
Hey,

Mullvad has performed a fair bit of updates since last update, would you mind regenerating its config?

Thanks!

**Comment by yitzhaq** [comment]
See #31 for details on how to grab updated configs, BTW, and let me know if it's stopped working.

**Comment by Zomboided** [comment]
Can't use 1234 anymore :-)  zip of the configs please

**Comment by yitzhaq** [comment]
https://mullvad.net/en/account/create/ will immediately spit out a reusable account number for you, zero questions asked. 123456 also seems to work, though there's no downside to having your own.

**Comment by Zomboided** [comment]
Done (eventually....) sorry I took so long, not focused on this at the moment.
