### ISSUE TITLE
IPVanish server list is out of date

### ISSUE THREAD

**Issue by Xennic** [Zomboided/service.vpn.manager.providers#61]
Some of the IPVanish servers are missing or won't connect. For example alot of the Netherlands Amsterdam ams-c servers aren't working.

**Comment by Zomboided** [comment]
I need the CA cert and the server list from this page please https://support.ipvanish.com/hc/en-us/articles/115002080733
I don't have an IPVanish accoutn to do this myself.

**Comment by Xennic** [comment]
Can you use this link that has the OpenVPN configs with embedded CA certs?

https://www.ipvanish.com/software/simpleconf/

**Comment by Zomboided** [comment]
Yup, that works great, thanks

**Comment by Zomboided** [comment]
Done
