### ISSUE TITLE
Windscribe configs need updating

### ISSUE THREAD

**Issue by Igor-Windscribe** [Zomboided/service.vpn.manager.providers#64]
We recently sunsetted our CA which has invalidated all the OpenVPN configs from before July 20th, including the ones integrated into the Zomboided VPN manager. Currently our customers who use this VPN manager are not able to connect to the VPN.

Can you please update the CA in the Windscribe folder as well as update the template for the configs? 

I've attached the new CA to this issue (renamed to a txt file): 
[ca.crt.txt](https://github.com/Zomboided/service.vpn.manager.providers/files/6888961/ca.crt.txt)

The new config template is as follows:
[TEMPLATE.txt](https://github.com/Zomboided/service.vpn.manager.providers/files/6889033/TEMPLATE.txt)

You can contact me directly at igor@windscribe.com if you have any questions or issues.

Thanks for your time. 
Igor M

**Comment by Zomboided** [comment]
Thanks Igor, have updated the files just now.
