### ISSUE TITLE
Refresh the list of IPVanish servers

### ISSUE THREAD

**Issue by kaos-ocs** [Zomboided/service.vpn.manager.providers#66]
The list below is programmatically built from the IPVanish list of servers downloaded on August 15, 2021. It replaces IPVanish/LOCATIONS.txt.

*NOTE*: Where there are duplicates of (country, city, server_number) I have used the higher letter. For example:
`ipvanish-US-New-York-nyc-a50` and `ipvanish-US-New-York-nyc-b50` both map to `United States - New York 50`, I used the entry for `b50` instead of `a50`.

[LOCATIONS.txt](https://github.com/Zomboided/service.vpn.manager.providers/files/6989822/LOCATIONS.txt)

**Comment by Zomboided** [comment]
Thanks for the heads up, it's all built programmatically anyway, so I just needed a one character change to fix this!
You should see this coming through shortly.
