### ISSUE TITLE
Add PIA Streaming Optimized Locations

### ISSUE THREAD

**Issue by beredim** [Zomboided/service.vpn.manager.providers#67]
The Windows client of PIA shows some so-called 'Streaming Optimized' VPN servers in some locations (like USA, UK etc).
Can these be added to the list?

**Comment by Zomboided** [comment]
https://www.privateinternetaccess.com/helpdesk/kb/articles/where-can-i-find-your-ovpn-files

No such options offered in any of the ovpn files that the add-on uses.  Doesn't surprise me, I suspect "Streaming Optimized" just changes the IP of the server it uses frequent and there's something else going on in their app to facilitate that churn.
