### ISSUE TITLE
VyprVPN depricated

### ISSUE THREAD

**Issue by ftisch-sbg** [Zomboided/service.vpn.manager.providers#70]
Hello Zomboided, 
first of all: Great work!
VyprVPN can't connect anymore with error: Provider depricated.
I tried to import the downloaded ovpn files manually, but connecting as user defined didn't work.
OpenVPN Log shows 
"Options error: --keepalive conflicts with --ping, --ping-exit or --ping-restart. If you use --keepalive you don't need any of the other --ping options."
I can't see any of these options in the ovpn-files, so plz do you have any suggestions?
[Vypr_OpenVPN_20200320.zip](https://github.com/Zomboided/service.vpn.manager.providers/files/12147430/Vypr_OpenVPN_20200320.zip)

**Comment by Zomboided** [comment]
See here https://github.com/Zomboided/service.vpn.manager/issues/390

**Comment by ftisch-sbg** [comment]
Thanks a lot for the fast help, the link helped me solving the issue!

I additionally had to delete the data-cipher and data-cipher-fallback lines since they led to option errors again.
By the way - the most recent ovpn-files are according to their support from 2020 - so there's actually no need marking them as deprecated ;)
Switching the connection still shows 'depricated provider' although having switched to user defined connection. But thats not a serious problem.
